### PR TITLE
s22-4pm-4: hn added showLeaderboard boolean variable to database

### LINKED ISSUE #19: LeaderBoard Field BackEnd
To the Backend for commons create, edit list, add a boolean field "ShowLeaderboard".

### PR DESCRIPTION
**Pull request by htn5**
The showLeaderboard field was added to the backend. This field can be manipulated using the update or create controllers.

The showLeaderboard variable for the update controller:
Screen Shot 2022-05-26 at 2 47 02 PM

The showLeaderboard variable for the create controller:
Screen Shot 2022-05-26 at 2 53 54 PM

The showLeaderboard variable in h2console:
Screen Shot 2022-05-26 at 2 50 41 PM

Closes #19

### CODE REVIEW

**Review by vmreed1 — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM... pending resolving the merge conflicts.

**Review by pconrad — APPROVED** [review]
LGTM!  Though I will want to test it on the qa site before merging.

**Comment by pconrad** [comment]
This is mergeable for 10 points as soon as CI/CD is finished :-)

**Pull request merged**
