### PR TITLE
s22-4pm-4: Zoey show leaderboard with common id Frontend

### PR DESCRIPTION
**Pull request by zoeyz5**
Finished show leaderboard in the list common fields with ids.
Each common will have its own leaderboard link which will lead to the leaderboard page for it.

before:
Screen Shot 2022-05-31 at 6 38 59 PM

after:
Screen Shot 2022-05-31 at 6 36 55 PM
Screen Shot 2022-05-31 at 6 36 48 PM

mutation tests:
Screen Shot 2022-05-31 at 4 34 54 PM

### CODE REVIEW

**Review by htn5 — CHANGES_REQUESTED** [review]
should change column name to something different since there will already be a showLeaderboard column

**Review by htn5 — COMMENTED** [review]
don't think DS_Store should be there. do you think you could get rid of as many of the commented out lines in AdminShowLeaderboardPage.js and AdminShowLeaderboard.test.js?

**Review by htn5 — DISMISSED** [review]
LGTM

**Review by andrewhlu — APPROVED** [review]
Tested on Heroku, confirmed that Leaderboard button is present / correct and links to a page with the commons ID embedded as a path variable. Thanks!

**Pull request merged**
