### PR TITLE
s22-4pm-3 ap - Unjoin Commons

### LINKED ISSUE #30: Make a button that allows the user to unjoin a commons
- [ ] user can be deleted from the commons database using the swagger backend
- [ ] button on the front end implemented that can call the database delete
- [ ] unjoin can only be called with a certain criteria so that it does not affect the commons

### PR DESCRIPTION
**Pull request by adampedersen**
**Summary**
In this PR, I add functionality to unjoin a commons on the login page. 

There is now a button next to the visit button on the left side of the home page.

The implementation uses a new type of commonsCard and commonsList (commonsCardVisit and commonsListVisit) in order to implement the list of cards that include the unjoin button.

As of now, the functionality is only available to Admin users. In the future this could be extended to all users, with a condition that the user has not been active in the common long enough for them to affect the tragedy of the commons natural aspect of the game.

The frontend button is the same in style as the visit button.

The function uses the database DELETE method accessed at `api/commons/{commonsId}/users/{userId}` and automatically updates the list after the delete is called.

The test files are created and almost completed. Tests are not passing due to an issue with accessing a user by currentuser.root.user This issue is possibly due to there not being available fixtures for what the access call the code is trying to make.

**Images**
image

**Storybook Link**
https://ucsb-cs156-s22.github.io/s22-4pm-happycows-docs-qa/

### CODE REVIEW

**Review by calvitronic — DISMISSED** [review]
Looks like everything works as expected after testing locally, just couldn't quite get all tests to pass yet. Still think this one deserves a shot.

**Review by calvitronic — DISMISSED** [review]
LGTM now that tests pass

**Review by adampedersen — COMMENTED** [review]
Good work on the testing Calvin

**Review by calvitronic — APPROVED** [review]

**Review by adampedersen — COMMENTED** [review]
LGTM

**Comment by pconrad** [comment]
This is a good idea... but we'll implement it from scratch, and think through both the workflow for a individual user to leave a commons, and for an admin for forcibly remove someone from a commons.

**Pull request closed without merging**
