### PR TITLE
s22-4pm-4: hn - showLeaderboard frontend

### PR DESCRIPTION
**Pull request by htn5**
Added the frontend fields for showLeaderboard in the create, edit, and list commons pages:
Screen Shot 2022-05-31 at 5 59 55 PM

Screen Shot 2022-05-31 at 6 01 38 PM

Screen Shot 2022-05-31 at 6 01 48 PM

### CODE REVIEW

**Review by aripo99 — DISMISSED** [review]
LGTM!

**Review by aripo99 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM---will deploy on QA

**Comment by htn5** [comment]
replaced with replaced by PR #54

**Pull request closed without merging**
