### PR TITLE
s22-4pm-3 cs - Leaderboard Fixtures Fixed: No duplicate User ID

### LINKED ISSUE #25: Add a React component for a leaderboard table. It should take a players array in the format for the leaderboard fixtures. Make sure it's in the storybook. The built in features of the table will allow sorting by cows, health, money, etc.
- [x] Add React Component
- [x] Create LeaderboardTable Stories
- [x] Implement sorting based off of certain attributes
- [x] Run "npm test and npm run coverage"
- [x] Run "npx stryker run"
- [x] Run "eslint --fix ."
- [x] Check on heroku-qa

### PR DESCRIPTION
**Pull request by charanpreet0**
# Overview

Changes the Leaderboard Fixtures file so there are is not a duplicate for the User ID

# Issues Addressed

Changed the duplicate "2" User ID to "3" in Leaderboard Fixtures

# Link to Storybook

https://ucsb-cs156-s22.github.io/s22-4pm-happycows-docs-qa/storybook-qa/Charanpreet-AddingLeaderboardReactComponent/?path=/story/components-leaderboard-leaderboardtable--empty

# Details
Before Fix
image

After Fix 
image

### CODE REVIEW

**Review by calvitronic — APPROVED** [review]
Super simple fix, as long as CI/CD is green LGTM!

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by sangitakunapuli** [comment]
specific to 4pm codebase; no need to reimplement

**Comment by pconrad** [comment]
Agree with @sangitakunapuli ... closing

**Pull request closed without merging**
