### PR TITLE
4pm-4: RobinW - corrected start date initialization in edit page

### PR DESCRIPTION
**Pull request by WangHaoranRobin**
The edit page did not correctly initialize the start date field;
Screen Shot 2022-06-01 at 5 39 18 PM
Now it initializes properly:
Screen Shot 2022-06-01 at 5 39 43 PM

The main reason for the bug was that the tests were written poorly: the mock API response did not match the actual API response.

closes: #36

### CODE REVIEW

**Review by htn5 — DISMISSED** [review]
nice job! LGTM

**Review by pconrad — COMMENTED** [review]
LGTM

**Review by htn5 — APPROVED** [review]
LGTM

**Comment by andrewhlu** [comment]
Merging with @phtcon's "LGTM" comment which was not marked as an approval in the GitHub UI.

**Pull request merged**
