### PR TITLE
s22-4pm-4: hn & ap Add checkbox for the showLeaderboard field 

### LINKED ISSUE #15: LeaderBoard Field Frontend
To the commons database table, add a boolean fields called show leaderboard. Edit the create and edit forms to show the showLeaderboard field.

### LINKED ISSUE #57: LeaderBoard Field Frontend Pt 2
Create a checkbox type field for the showLeaderboard field.

### PR DESCRIPTION
**Pull request by aripo99**
# Overview

Add checkbox for the showLeaderboard field for both editing and creating Commons.

# Issues Addressed

Previously we used a string 'false' or 'true'

# Details

Before:
Screen Shot 2022-06-01 at 10 20 14 AM

Screen Shot 2022-06-01 at 10 19 52 AM

After:
Screen Shot 2022-06-01 at 10 18 13 AM

Screen Shot 2022-06-01 at 10 18 39 AM

Closes #15 
Closes #57

### CODE REVIEW

**Review by htn5 — APPROVED** [review]
LGTM

**Review by htn5 — COMMENTED** [review]
delete commented code in AdminCreateCommonsPage.test.js

**Review by pconrad — APPROVED** [review]
LGTM

**Review by vmreed1 — APPROVED** [review]
LGTM

**Pull request merged**
