### PR TITLE
s22-4pm-3 happycows: AP changes made to AppNavbar.stories.js according to…

### PR DESCRIPTION
**Pull request by adampedersen**
In this PR, we add a few additional stories to the storybook for the navbar.

The additional stories show the navbar under various conditions that we were not showing before:

- Logged in as an admin
- Logged in as a regular user
- When the H2 and Swagger links are present or absent in all possible combinations
- The purpose is to allow us to visualize changes to the navbar in later stories more easily.

### CODE REVIEW

**Review by KelvinZhang123 — COMMENTED** [review]
looks good so far, will wait for final 2 checks to pass before confirming merge

**Comment by KelvinZhang123** [comment]
LGTM!!

**Review by charanpreet0 — APPROVED** [review]
LGTM! Everything looks good!

**Review by KelvinZhang123 — APPROVED** [review]
LGTM!

**Comment by pconrad** [comment]
Closing... 4pm-3 already did this.

**Pull request closed without merging**
